<?php

namespace ContainerHTOZUMa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNouvelUtilisateurTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\NouvelUtilisateurType' shared autowired service.
     *
     * @return \App\Form\NouvelUtilisateurType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\NouvelUtilisateurType'] = new \App\Form\NouvelUtilisateurType();
    }
}
