<?php

namespace ContainerHTOZUMa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlatPersisterService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\State\PlatPersister' shared autowired service.
     *
     * @return \App\State\PlatPersister
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\State\\PlatPersister'] = new \App\State\PlatPersister();
    }
}
