<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHTOZUMa\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHTOZUMa/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerHTOZUMa.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerHTOZUMa\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerHTOZUMa\App_KernelProdContainer([
    'container.build_hash' => 'HTOZUMa',
    'container.build_id' => '13e57b9e',
    'container.build_time' => 1683748502,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHTOZUMa');
