<?php

namespace Container7vOZEvP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEasyAdminSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\EasyAdminSubscriber' shared autowired service.
     *
     * @return \App\EventListener\EasyAdminSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/EasyAdminSubscriber.php';

        return $container->privates['App\\EventListener\\EasyAdminSubscriber'] = new \App\EventListener\EasyAdminSubscriber(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));
    }
}
