<?php

namespace Container7vOZEvP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNouvelUtilisateurTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\NouvelUtilisateurType' shared autowired service.
     *
     * @return \App\Form\NouvelUtilisateurType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/NouvelUtilisateurType.php';

        return $container->privates['App\\Form\\NouvelUtilisateurType'] = new \App\Form\NouvelUtilisateurType();
    }
}
