<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Restaurant extends \App\Entity\Restaurant implements \Doctrine\Persistence\Proxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
        __clone as private __doClone;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'couverts' => [parent::class, 'couverts', null],
        "\0".parent::class."\0".'ferm_midi' => [parent::class, 'ferm_midi', null],
        "\0".parent::class."\0".'ferm_soir' => [parent::class, 'ferm_soir', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'ouv_midi' => [parent::class, 'ouv_midi', null],
        "\0".parent::class."\0".'ouv_soir' => [parent::class, 'ouv_soir', null],
        'couverts' => [parent::class, 'couverts', null],
        'ferm_midi' => [parent::class, 'ferm_midi', null],
        'ferm_soir' => [parent::class, 'ferm_soir', null],
        'id' => [parent::class, 'id', null],
        'nom' => [parent::class, 'nom', null],
        'ouv_midi' => [parent::class, 'ouv_midi', null],
        'ouv_soir' => [parent::class, 'ouv_soir', null],
    ];

    /**
     * @internal
     */
    public bool $__isCloning = false;

    public function __construct(?\Closure $initializer = null)
    {
        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
            '__isCloning' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __clone()
    {
        $this->__isCloning = true;

        try {
            $this->__doClone();
        } finally {
            $this->__isCloning = false;
        }
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
